# Generated by Django 4.2.4 on 2023-10-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_user_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.CharField(choices=[('policy', 'Политика'), ('culture', 'Культура'), ('science', 'Наука'), ('sport', 'Спорт'), ('technology', 'Технологии')], default=('SC',), max_length=10),
        ),
    ]
