# Generated by Django 4.2.4 on 2023-10-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_name_author_user_remove_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='comment_time_in',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date_in',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='rating_news',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='article_news',
            field=models.CharField(choices=[('Article', 'Статья'), ('News', 'Новость')], default='NW', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.CharField(choices=[('policy', 'Политика'), ('culture', 'Культура'), ('education', 'Образование'), ('sport', 'Спорт'), ('technology', 'Технологии')], default='SP', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
    ]
